os: linux
dist: bionic
language: python

jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=py37

    - python: 3.8
      env: TOXENV=py38

    - python: 3.8.6
      env: TOXENV=py38

    - python: 3.9.0
      env: TOXENV=py38

    - python: 3.8
      env: TOXENV=lint

    - python: 3.8
      env: TOXENV=black

install: pip install -U setuptools tox coveralls
script: tox
after_success: coveralls
